
###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/61acc7a0641d5bd8e7da2bda

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Arto Helas",
    "number": "14111999"
}

###
PUT http://localhost:3001/api/persons/61acc7a0641d5bd8e7da2bda
Content-Type: application/json

{
    "name": "Arto Helasb"

}
